# Generated by Django 5.0.3 on 2024-05-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jenis', models.CharField(choices=[('Putra', 'Putra'), ('Putri', 'Putri')], max_length=10)),
                ('harga_per_tahun', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sisa_kamar', models.PositiveIntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('fasilitas', models.JSONField(blank=True, null=True)),
                ('peraturan', models.JSONField(blank=True, null=True)),
                ('persyaratan', models.JSONField(blank=True, null=True)),
                ('suka', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FotoKos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_kos/')),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True)),
                ('kos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='baiqkos_app.kos')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pesan', models.DateField(auto_now_add=True)),
                ('penyewa', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('mulai_sewa', models.DateField()),
                ('nomor_hp', models.CharField(max_length=15)),
                ('bukti_pembayaran', models.ImageField(upload_to='bukti_pembayaran/')),
                ('ktp', models.ImageField(upload_to='ktp/')),
                ('kos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baiqkos_app.kos')),
            ],
        ),
    ]
