# Generated by Django 5.0.3 on 2024-05-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiqkos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kos',
            name='fasilitas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kos',
            name='peraturan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kos',
            name='persyaratan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
