# Generated by Django 5.0.3 on 2024-05-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiqkos_app', '0003_alter_kos_harga_per_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='kos',
            name='pemilik',
            field=models.CharField(default='Anonim', max_length=50),
        ),
    ]
