# Generated by Django 5.0.3 on 2024-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiqkos_app', '0005_pemesanan_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_pesan',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
