# Generated by Django 5.0.3 on 2024-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiqkos_app', '0007_alter_kos_alamat_alter_kos_pemilik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kos',
            name='persyaratan',
            field=models.TextField(blank=True, default='Bisa bayar DP (uang muka) : 30% dari biaya yang dipilih', null=True),
        ),
    ]
