# Generated by Django 5.0.3 on 2024-05-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiqkos_app', '0009_remove_kos_pemilik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemilik', models.CharField(default='Bapak', max_length=100)),
                ('nomor_hp', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='kos',
            name='persyaratan',
            field=models.TextField(blank=True, default='Bisa bayar DP (uang muka) : 30%', null=True),
        ),
        migrations.AddField(
            model_name='kos',
            name='pemilik',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='baiqkos_app.pemilik'),
            preserve_default=False,
        ),
    ]
