# Generated by Django 5.0.3 on 2024-05-07 08:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baiqkos_app', '0011_alter_pemilik_nomor_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kos',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kos',
            name='fasilitas',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kos',
            name='peraturan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kos',
            name='persyaratan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
